### ISSUE TITLE
Show All Extensions EA not working

### ISSUE THREAD

**Issue by n0brainer** [franton/CIS-Apple-Security-Casper#9]
I was able to get the script to work with some modifications (I will submit a separate issue with the changes), but the EA reports Disabled.  I assume because the script is changing NSGlobalDomain and the EA is looking at com.apple.finder.  I changed the EA to look at NSGlobalDomain but it is still showing as disabled.

On the local machine I can do the defaults read NSGlobalDomain and it shows properly enabled (result of: 1) whereas com.apple.finder is showing a result of 0

**Comment by franton** [comment]
The code on both sides is working properly. You have to kill and relaunch the finder to see any change in behaviour.
